[package]
name = "kiyomi"
version = "0.1.0"
edition = "2021"
description = "Game engine for learning and personal use"
exclude = [".github/**/*", "crates/**/*"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/studio-citrus/kiyomi"

[dependencies]
